# Generated by Django 4.2.1 on 2023-09-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaining_quantity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.BigIntegerField(null=True),
        ),
    ]
