# Generated by Django 4.2.1 on 2023-09-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_remaining_quantity_product_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='remaining_quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
